# Generated by Django 3.1.2 on 2022-01-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blog_posts", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="subtitle",
            field=models.CharField(default="TEST", max_length=500),
            preserve_default=False,
        )
    ]
