# Generated by Django 3.1.2 on 2021-12-22 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("blog_posts", "0002_auto_20211219_1344")]

    operations = [
        migrations.CreateModel(
            name="ImageBlogPost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="blog_pics/")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="blog_posts.blogpost",
                    ),
                ),
            ],
        )
    ]
