# Generated by Django 3.2 on 2022-01-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blog_posts", "0003_auto_20220107_1446")]

    operations = [
        migrations.AlterField(
            model_name="imageblogpost",
            name="image",
            field=models.FileField(upload_to="blog_pics/"),
        )
    ]
