# Generated by Django 3.1.2 on 2021-12-31 11:04

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [("blog_posts", "0003_imageblogpost")]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="post_content",
            field=django_quill.fields.QuillField(),
        ),
        migrations.DeleteModel(name="ImageBlogPost"),
    ]
