# Generated by Django 3.1.2 on 2021-12-31 11:26

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [("blog_posts", "0004_auto_20211231_1104")]

    operations = [
        migrations.CreateModel(
            name="QuillPost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", django_quill.fields.QuillField()),
            ],
        )
    ]
