# Generated by Django 3.1.2 on 2021-01-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("display_name", models.CharField(max_length=100)),
            ],
        )
    ]
