# Generated by Django 3.1.2 on 2021-01-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("author_page", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="author", name="bio", field=models.TextField(default="")
        )
    ]
