# Generated by Django 3.1.2 on 2021-03-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("author_page", "0002_author_bio")]

    operations = [
        migrations.AddField(
            model_name="author",
            name="twitter_handle",
            field=models.CharField(blank=True, default="", max_length=50),
        )
    ]
