# Generated by Django 3.0.6 on 2020-05-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_with_grid', '0002_auto_20200514_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='grid_path',
            field=models.FilePathField(match='.*.puz', path='/home/antoine/static/puzzle'),
        ),
    ]
