# Generated by Django 3.0.6 on 2020-05-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_with_grid', '0005_project_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.CharField(default='Antoine HINGE', max_length=25),
            preserve_default=False,
        ),
    ]
