# Generated by Django 3.0.6 on 2020-08-26 19:37

from django.db import migrations, models
import post_with_grid.models


class Migration(migrations.Migration):

    dependencies = [
        ('post_with_grid', '0011_edito'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='crossword_type',
            field=models.IntegerField(choices=[(post_with_grid.models.CrosswordsType['CLASSIC'], 'Classique'), (post_with_grid.models.CrosswordsType['CRYPTIC'], 'Cryptique')], default=0),
        ),
    ]
