# Generated by Django 3.1 on 2020-08-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_with_grid', '0012_project_crossword_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='grid_size',
            field=models.IntegerField(choices=[(0, 'Petite'), (1, 'Moyenne'), (2, 'Grande'), (3, 'Très grande')], default=0),
        ),
    ]
