# Generated by Django 3.1.2 on 2020-10-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_with_grid', '0013_project_grid_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid', models.IntegerField()),
                ('pseudo', models.CharField(max_length=25)),
                ('time', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
            options={
                'unique_together': {('grid', 'pseudo')},
            },
        ),
    ]
