# Generated by Django 3.1.2 on 2020-10-20 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post_with_grid', '0014_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='solved_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
