# Generated by Django 3.1.2 on 2020-12-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("post_with_grid", "0015_score_solved_at")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="twitter_card_clue",
            field=models.CharField(default="Grille de mots croisés", max_length=200),
        )
    ]
