# Generated by Django 3.1.2 on 2021-01-18 09:49

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("post_with_grid", "0017_auto_20210103_1826")]

    operations = [
        migrations.CreateModel(
            name="MetaGrid",
            fields=[
                (
                    "project_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="post_with_grid.project",
                    ),
                ),
                (
                    "meta_answers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50), size=None
                    ),
                ),
            ],
            bases=("post_with_grid.project",),
        )
    ]
