# Generated by Django 3.1.2 on 2021-01-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("post_with_grid", "0018_metagrid")]

    operations = [
        migrations.AddField(
            model_name="metagrid",
            name="meta_question",
            field=models.CharField(default="La réponse est simple!", max_length=200),
        ),
        migrations.AlterField(
            model_name="project",
            name="crossword_type",
            field=models.IntegerField(
                choices=[(0, "Classique"), (1, "Cryptique"), (2, "Méta")], default=0
            ),
        ),
    ]
