# Generated by Django 3.1.2 on 2021-03-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("post_with_grid", "0019_auto_20210118_2048")]

    operations = [
        migrations.AddField(
            model_name="metagrid",
            name="meta_explanation",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="metagrid",
            name="meta_solution_picture",
            field=models.ImageField(default="none.png", upload_to="meta_img/"),
        ),
    ]
