# Generated by Django 3.1.2 on 2021-03-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("post_with_grid", "0020_auto_20210315_1817")]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grid_key", models.IntegerField()),
                ("pseudo", models.CharField(max_length=25)),
                ("comment", models.CharField(max_length=480)),
                ("commented_at", models.DateTimeField(auto_now_add=True)),
            ],
        )
    ]
