# Generated by Django 3.1.2 on 2021-04-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("post_with_grid", "0021_comment")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="download_count",
            field=models.IntegerField(default=0),
        )
    ]
