# Generated by Django 3.1.2 on 2021-07-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("post_with_grid", "0022_project_download_count")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="grid_information",
            field=models.TextField(default=""),
        )
    ]
