# Generated by Django 3.1.2 on 2021-07-12 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("post_with_grid", "0023_project_grid_information")]

    operations = [migrations.RemoveField(model_name="metagrid", name="meta_question")]
