# Generated by Django 3.1.2 on 2021-07-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("post_with_grid", "0024_remove_metagrid_meta_question")]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="grid_information",
            field=models.TextField(blank=True, default=""),
        )
    ]
