# Generated by Django 3.1.2 on 2021-09-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("post_with_grid", "0025_auto_20210712_0909")]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="crossword_type",
            field=models.IntegerField(
                choices=[
                    (0, "Classique"),
                    (1, "Cryptique"),
                    (2, "Méta"),
                    (3, "Scrabeille"),
                ],
                default=0,
            ),
        )
    ]
