# Generated by Django 3.2 on 2022-01-13 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("post_with_grid", "0027_alter_project_twitter_card_clue")]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="date_created",
            field=models.DateField(default=django.utils.timezone.now),
        )
    ]
