# Generated by Django 3.2 on 2022-05-10 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("post_with_grid", "0028_alter_project_date_created")]

    operations = [migrations.DeleteModel(name="Edito")]
