# Generated by Django 3.2 on 2022-05-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("post_with_grid", "0029_delete_edito")]

    operations = [
        migrations.AddField(
            model_name="score",
            name="got_help",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="score",
            name="private_leaderboard",
            field=models.CharField(default="", max_length=100),
        ),
    ]
