# Generated by Django 3.2 on 2022-05-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("post_with_grid", "0030_auto_20220510_1021")]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="private_leaderboard",
            field=models.CharField(blank=True, default="", max_length=100),
        )
    ]
