# Generated by Django 3.2 on 2022-06-24 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("post_with_grid", "0031_alter_score_private_leaderboard")]

    operations = [migrations.RemoveField(model_name="project", name="download_count")]
